version: 2
jobs:
  minecraft_server:
    docker:
      - image: circleci/buildpack-deps:19.10
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build image
          command: docker build -t mc:$CIRCLE_BUILD_NUM .

workflows:
  version: 2
  build:
    jobs:
      - minecraft_server
